### ISSUE TITLE
Enhance the CLI commands usage for parsing the policies via flags

### ISSUE THREAD

**Issue by santoshkal** [intelops/genval#89]
The `policy` flag should accept a YAML file with the following structure.

```yaml
name: ac
description: 
version: v1.0.0
policies:
- location of policy 1
- location of policy 2
- location of policy 3
```
The policy field in the YAML will contain the location of policy files stored either in local FS or URLs like Github.
